<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Common\Models\" />
    <Folder Include="Features\Authentication\Queries\" />
    <Folder Include="Features\Permissions\Commands\" />
    <Folder Include="Mappers\" />
    <Folder Include="DTOs\" />
    <Folder Include="Validators\" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentResults" Version="4.0.0" />
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\CoreUtilities\CoreUtilities.csproj" />
    <ProjectReference Include="..\SharedServices.Core\SharedServices.Core.csproj" />
  </ItemGroup>

</Project>
