<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="FluentResults" Version="4.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="9.0.7" />
		<PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
		<PackageReference Include="Grpc.AspNetCore.HealthChecks" Version="2.71.0" />
		<PackageReference Include="Grpc.Tools" Version="2.72.0" PrivateAssets="All" />
	</ItemGroup>

	<ItemGroup>
		<Protobuf Include="GrpcProtos\email.proto" GrpcServices="Both" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Interfaces\" />
	  <Folder Include="Services\" />
	</ItemGroup>

</Project>
